// src/games/quiz/quizFallbackBank.js
// Large built-in question bank used when Gemini API is unavailable.
// ~20 questions per topic, shuffled and sliced to the requested count.

const BANK = {
  'General Knowledge': [
    { question: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2 },
    { question: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correctIndex: 1 },
    { question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Mars', 'Saturn'], correctIndex: 2 },
    { question: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'], correctIndex: 2 },
    { question: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctIndex: 3 },
    { question: 'In which year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctIndex: 2 },
    { question: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correctIndex: 2 },
    { question: 'How many bones are in the adult human body?', options: ['196', '206', '216', '226'], correctIndex: 1 },
    { question: 'Which country invented paper?', options: ['Egypt', 'India', 'China', 'Greece'], correctIndex: 2 },
    { question: 'What is the smallest country in the world?', options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'], correctIndex: 2 },
    { question: 'Which element has the symbol O?', options: ['Gold', 'Osmium', 'Oxygen', 'Oxide'], correctIndex: 2 },
    { question: 'How many continents are there?', options: ['5', '6', '7', '8'], correctIndex: 2 },
    { question: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctIndex: 1 },
    { question: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correctIndex: 2 },
    { question: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], correctIndex: 2 },
    { question: 'How many zeros are in one million?', options: ['5', '6', '7', '8'], correctIndex: 1 },
    { question: 'What is the currency of Japan?', options: ['Yuan', 'Won', 'Yen', 'Ringgit'], correctIndex: 2 },
    { question: 'Which planet is closest to the Sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], correctIndex: 2 },
    { question: 'Who wrote Romeo and Juliet?', options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Homer'], correctIndex: 1 },
    { question: 'What is the boiling point of water in Celsius?', options: ['90°C', '95°C', '100°C', '110°C'], correctIndex: 2 },
  ],
  'Science': [
    { question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Vacuole'], correctIndex: 2 },
    { question: 'What is the speed of light (approx) in km/s?', options: ['200,000', '300,000', '400,000', '500,000'], correctIndex: 1 },
    { question: 'What force keeps planets in orbit around the sun?', options: ['Magnetism', 'Friction', 'Gravity', 'Electrostatics'], correctIndex: 2 },
    { question: 'What is the atomic number of Carbon?', options: ['4', '6', '8', '12'], correctIndex: 1 },
    { question: 'Which scientist proposed the theory of relativity?', options: ['Newton', 'Bohr', 'Einstein', 'Hawking'], correctIndex: 2 },
    { question: 'What type of wave is sound?', options: ['Transverse', 'Electromagnetic', 'Longitudinal', 'Gamma'], correctIndex: 2 },
    { question: 'What is H2O commonly known as?', options: ['Salt', 'Water', 'Hydrogen gas', 'Acid'], correctIndex: 1 },
    { question: 'What is the process by which plants make food?', options: ['Respiration', 'Digestion', 'Photosynthesis', 'Transpiration'], correctIndex: 2 },
    { question: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctIndex: 1 },
    { question: 'What is the most abundant gas in Earth\'s atmosphere?', options: ['Oxygen', 'Carbon Dioxide', 'Argon', 'Nitrogen'], correctIndex: 3 },
    { question: 'What is the unit of electrical resistance?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], correctIndex: 2 },
    { question: 'DNA stands for?', options: ['Deoxyribonucleic Acid', 'Dinitrogen Acid', 'Dynamic Nucleic Acid', 'Dense Nuclear Atom'], correctIndex: 0 },
    { question: 'What is the pH of pure water?', options: ['5', '6', '7', '8'], correctIndex: 2 },
    { question: 'Which organ produces insulin?', options: ['Liver', 'Kidney', 'Pancreas', 'Heart'], correctIndex: 2 },
    { question: 'What is the chemical formula for table salt?', options: ['KCl', 'NaCl', 'CaCl2', 'MgCl2'], correctIndex: 1 },
    { question: 'What is absolute zero in Celsius?', options: ['-173°C', '-223°C', '-273°C', '-323°C'], correctIndex: 2 },
    { question: 'How many chambers does a human heart have?', options: ['2', '3', '4', '5'], correctIndex: 2 },
    { question: 'What is the largest planet in our solar system?', options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'], correctIndex: 1 },
    { question: 'Which vitamin is produced by the skin in sunlight?', options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], correctIndex: 3 },
    { question: 'What is the unit of frequency?', options: ['Newton', 'Pascal', 'Hertz', 'Joule'], correctIndex: 2 },
  ],
  'History': [
    { question: 'In which year did India gain independence?', options: ['1945', '1946', '1947', '1948'], correctIndex: 2 },
    { question: 'Who was the first President of the United States?', options: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams'], correctIndex: 1 },
    { question: 'The Great Wall of China was built to protect against whom?', options: ['Mongols', 'Japanese', 'Persians', 'Romans'], correctIndex: 0 },
    { question: 'In which year did the French Revolution begin?', options: ['1776', '1783', '1789', '1799'], correctIndex: 2 },
    { question: 'Who was the first man to walk on the Moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'], correctIndex: 2 },
    { question: 'Which empire was ruled by Julius Caesar?', options: ['Greek', 'Ottoman', 'Roman', 'Byzantine'], correctIndex: 2 },
    { question: 'When did World War I begin?', options: ['1912', '1914', '1916', '1918'], correctIndex: 1 },
    { question: 'Which country was Nelson Mandela president of?', options: ['Kenya', 'Nigeria', 'South Africa', 'Zimbabwe'], correctIndex: 2 },
    { question: 'Who discovered America in 1492?', options: ['Amerigo Vespucci', 'Vasco da Gama', 'Christopher Columbus', 'Ferdinand Magellan'], correctIndex: 2 },
    { question: 'The Berlin Wall fell in which year?', options: ['1987', '1988', '1989', '1990'], correctIndex: 2 },
    { question: 'Who was the first female Prime Minister of the UK?', options: ['Theresa May', 'Margaret Thatcher', 'Liz Truss', 'Eleanor Roosevelt'], correctIndex: 1 },
    { question: 'Which ancient wonder was located in Alexandria?', options: ['Hanging Gardens', 'Colossus of Rhodes', 'Lighthouse of Alexandria', 'Temple of Artemis'], correctIndex: 2 },
    { question: 'In which year did the Titanic sink?', options: ['1910', '1911', '1912', '1913'], correctIndex: 2 },
    { question: 'Who was the last pharaoh of ancient Egypt?', options: ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Ramesses II'], correctIndex: 1 },
    { question: 'Which country first landed a rover on Mars?', options: ['Russia', 'China', 'USA', 'India'], correctIndex: 2 },
    { question: 'The Renaissance began in which country?', options: ['France', 'Germany', 'Italy', 'Spain'], correctIndex: 2 },
    { question: 'Who gave the "I Have a Dream" speech?', options: ['Malcolm X', 'Nelson Mandela', 'Martin Luther King Jr.', 'Barack Obama'], correctIndex: 2 },
    { question: 'Which country launched the first satellite Sputnik?', options: ['USA', 'Germany', 'Russia', 'China'], correctIndex: 2 },
    { question: 'The Magna Carta was signed in which year?', options: ['1115', '1215', '1315', '1415'], correctIndex: 1 },
    { question: 'Who was Adolf Hitler\'s political party?', options: ['Communist Party', 'Labour Party', 'National Socialist (Nazi) Party', 'Fascist Party'], correctIndex: 2 },
  ],
  'Geography': [
    { question: 'What is the capital of Brazil?', options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'], correctIndex: 2 },
    { question: 'Which is the largest desert in the world?', options: ['Sahara', 'Arabian', 'Gobi', 'Antarctic'], correctIndex: 3 },
    { question: 'Mount Everest is in which mountain range?', options: ['Andes', 'Alps', 'Himalayas', 'Rockies'], correctIndex: 2 },
    { question: 'Which country has the most natural lakes?', options: ['USA', 'Russia', 'Canada', 'Brazil'], correctIndex: 2 },
    { question: 'What is the capital of Canada?', options: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3 },
    { question: 'The Amazon rainforest is primarily in which country?', options: ['Colombia', 'Peru', 'Brazil', 'Venezuela'], correctIndex: 2 },
    { question: 'Which country has the longest coastline?', options: ['Russia', 'Australia', 'Norway', 'Canada'], correctIndex: 3 },
    { question: 'What is the smallest continent?', options: ['Europe', 'Antarctica', 'Australia', 'South America'], correctIndex: 2 },
    { question: 'Which river flows through Egypt?', options: ['Congo', 'Niger', 'Nile', 'Zambezi'], correctIndex: 2 },
    { question: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Hiroshima'], correctIndex: 2 },
    { question: 'Which country is the largest by land area?', options: ['China', 'USA', 'Canada', 'Russia'], correctIndex: 3 },
    { question: 'The Sahara Desert is located on which continent?', options: ['Asia', 'Australia', 'Africa', 'South America'], correctIndex: 2 },
    { question: 'What is the tallest mountain in Africa?', options: ['Mount Kenya', 'Mount Kilimanjaro', 'Mount Elgon', 'Ras Dashen'], correctIndex: 1 },
    { question: 'Which ocean is the smallest?', options: ['Atlantic', 'Indian', 'Southern', 'Arctic'], correctIndex: 3 },
    { question: 'What country does Greenland belong to?', options: ['Norway', 'Iceland', 'Canada', 'Denmark'], correctIndex: 3 },
    { question: 'Which city is known as the City of Love?', options: ['Rome', 'Venice', 'Paris', 'Barcelona'], correctIndex: 2 },
    { question: 'The Great Barrier Reef is located in which country?', options: ['New Zealand', 'Fiji', 'Australia', 'Indonesia'], correctIndex: 2 },
    { question: 'What is the capital of South Africa\'s government?', options: ['Cape Town', 'Johannesburg', 'Pretoria', 'Durban'], correctIndex: 2 },
    { question: 'Which is the most populated city in the world?', options: ['Beijing', 'Mumbai', 'Tokyo', 'Shanghai'], correctIndex: 2 },
    { question: 'The Eiffel Tower is located in which city?', options: ['London', 'Berlin', 'Rome', 'Paris'], correctIndex: 3 },
  ],
  'Sports': [
    { question: 'How many players are in a standard football (soccer) team?', options: ['9', '10', '11', '12'], correctIndex: 2 },
    { question: 'In which sport is a shuttlecock used?', options: ['Tennis', 'Squash', 'Badminton', 'Pickleball'], correctIndex: 2 },
    { question: 'How many rings are on the Olympic flag?', options: ['4', '5', '6', '7'], correctIndex: 1 },
    { question: 'Which country invented cricket?', options: ['Australia', 'India', 'England', 'West Indies'], correctIndex: 2 },
    { question: 'How long is a standard marathon in km?', options: ['40.1 km', '41.1 km', '42.2 km', '43.2 km'], correctIndex: 2 },
    { question: 'In basketball, how many points is a three-pointer worth?', options: ['1', '2', '3', '4'], correctIndex: 2 },
    { question: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Argentina', 'Brazil', 'Italy'], correctIndex: 2 },
    { question: 'How many sets are in a standard tennis grand slam final for men?', options: ['3', '4', '5', '6'], correctIndex: 2 },
    { question: 'What is the diameter of a basketball hoop in inches?', options: ['14 inches', '16 inches', '18 inches', '20 inches'], correctIndex: 2 },
    { question: 'Which sport uses a puck?', options: ['Polo', 'Lacrosse', 'Ice Hockey', 'Field Hockey'], correctIndex: 2 },
    { question: 'How many players are on a baseball team?', options: ['7', '8', '9', '10'], correctIndex: 2 },
    { question: 'The Tour de France is a competition in which sport?', options: ['Running', 'Swimming', 'Cycling', 'Triathlon'], correctIndex: 2 },
    { question: 'In which sport would you perform a slam dunk?', options: ['Volleyball', 'Basketball', 'Tennis', 'Handball'], correctIndex: 1 },
    { question: 'How many holes are in a standard golf course?', options: ['16', '17', '18', '19'], correctIndex: 2 },
    { question: 'Which country hosts the Wimbledon tennis tournament?', options: ['USA', 'France', 'Australia', 'England'], correctIndex: 3 },
    { question: 'What shape is a cricket pitch?', options: ['Square', 'Oval', 'Circle', 'Rectangle'], correctIndex: 1 },
    { question: 'In F1, how many points does a race winner receive?', options: ['20', '22', '25', '30'], correctIndex: 2 },
    { question: 'Which country is known as the "All Blacks" in rugby?', options: ['Australia', 'South Africa', 'England', 'New Zealand'], correctIndex: 3 },
    { question: 'What is the highest score possible in a single dart throw?', options: ['50', '57', '60', '72'], correctIndex: 2 },
    { question: 'The first modern Olympic Games were held in which city?', options: ['London', 'Paris', 'Athens', 'Rome'], correctIndex: 2 },
  ],
  'Movies & TV': [
    { question: 'Who directed Jurassic Park?', options: ['James Cameron', 'Steven Spielberg', 'George Lucas', 'Ridley Scott'], correctIndex: 1 },
    { question: 'What is the highest-grossing film of all time?', options: ['Titanic', 'Avengers: Endgame', 'Avatar', 'Star Wars'], correctIndex: 2 },
    { question: 'In The Lion King, what is Simba\'s father\'s name?', options: ['Scar', 'Rafiki', 'Mufasa', 'Zazu'], correctIndex: 2 },
    { question: 'Which actor plays Iron Man in the MCU?', options: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2 },
    { question: 'What film features the quote "You\'re gonna need a bigger boat"?', options: ['The Poseidon Adventure', 'Jaws', 'Deep Blue Sea', 'The Abyss'], correctIndex: 1 },
    { question: 'The TV show "Breaking Bad" is set in which city?', options: ['Phoenix', 'Las Vegas', 'El Paso', 'Albuquerque'], correctIndex: 3 },
    { question: 'In how many films did Audrey Hepburn win an Oscar for acting?', options: ['0', '1', '2', '3'], correctIndex: 1 },
    { question: 'Who played Jack Sparrow in Pirates of the Caribbean?', options: ['Brad Pitt', 'Tom Hanks', 'Johnny Depp', 'Orlando Bloom'], correctIndex: 2 },
    { question: 'Which streaming service produced Stranger Things?', options: ['HBO', 'Amazon Prime', 'Netflix', 'Disney+'], correctIndex: 2 },
    { question: 'What is the name of the fictional African country in Black Panther?', options: ['Zamunda', 'Genovia', 'Wakanda', 'Narnia'], correctIndex: 2 },
    { question: 'Which movie features the song "Let It Go"?', options: ['Tangled', 'Moana', 'Frozen', 'Brave'], correctIndex: 2 },
    { question: 'Who voiced Woody in Toy Story?', options: ['Tom Hanks', 'Tim Allen', 'John Lasseter', 'Billy Crystal'], correctIndex: 0 },
    { question: 'Game of Thrones is based on books by which author?', options: ['J.R.R. Tolkien', 'George R.R. Martin', 'Terry Pratchett', 'Robert Jordan'], correctIndex: 1 },
    { question: 'What year was the first Star Wars film released?', options: ['1975', '1976', '1977', '1978'], correctIndex: 2 },
    { question: 'In The Office (US), what company do they work for?', options: ['Initech', 'Stark Industries', 'Dunder Mifflin', 'Prestige Worldwide'], correctIndex: 2 },
    { question: 'Which actor plays Batman in The Dark Knight?', options: ['Ben Affleck', 'Michael Keaton', 'Christian Bale', 'Val Kilmer'], correctIndex: 2 },
    { question: 'The Shawshank Redemption is based on a story by which author?', options: ['Dean Koontz', 'Stephen King', 'John Grisham', 'Michael Crichton'], correctIndex: 1 },
    { question: 'What is the highest-rated TV show on IMDb?', options: ['The Wire', 'Breaking Bad', 'Game of Thrones', 'The Sopranos'], correctIndex: 1 },
    { question: 'In Friends, what is the name of Ross\'s pet monkey?', options: ['Marcel', 'Max', 'Marco', 'Mario'], correctIndex: 0 },
    { question: 'Which film won Best Picture at the 2020 Oscars?', options: ['1917', 'Joker', 'Once Upon a Time in Hollywood', 'Parasite'], correctIndex: 3 },
  ],
  'Music': [
    { question: 'Which band wrote "Bohemian Rhapsody"?', options: ['The Beatles', 'Led Zeppelin', 'Queen', 'The Rolling Stones'], correctIndex: 2 },
    { question: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], correctIndex: 2 },
    { question: 'Michael Jackson\'s "Thriller" was released in which year?', options: ['1980', '1981', '1982', '1983'], correctIndex: 2 },
    { question: 'Who is the best-selling music artist of all time?', options: ['Michael Jackson', 'Elvis Presley', 'The Beatles', 'Madonna'], correctIndex: 2 },
    { question: 'Which country is K-Pop music originally from?', options: ['Japan', 'China', 'South Korea', 'Taiwan'], correctIndex: 2 },
    { question: 'How many keys does a standard piano have?', options: ['76', '80', '88', '92'], correctIndex: 2 },
    { question: 'Who sang "Rolling in the Deep"?', options: ['Beyoncé', 'Rihanna', 'Adele', 'Amy Winehouse'], correctIndex: 2 },
    { question: 'What instrument does Yo-Yo Ma play?', options: ['Violin', 'Cello', 'Viola', 'Double Bass'], correctIndex: 1 },
    { question: 'Which music festival is held in Glastonbury, England?', options: ['Coachella', 'Glastonbury Festival', 'Lollapalooza', 'Reading Festival'], correctIndex: 1 },
    { question: 'Who composed Symphony No. 5?', options: ['Mozart', 'Bach', 'Beethoven', 'Chopin'], correctIndex: 2 },
    { question: 'What does BPM stand for in music?', options: ['Bass Per Minute', 'Beats Per Measure', 'Beats Per Minute', 'Band Per Music'], correctIndex: 2 },
    { question: 'Taylor Swift\'s album "1989" is named after what?', options: ['A song title', 'Her birth year', 'A band name', 'A concert year'], correctIndex: 1 },
    { question: 'Which instrument has black and white keys?', options: ['Harp', 'Piano', 'Ukulele', 'Banjo'], correctIndex: 1 },
    { question: 'The Grammy Awards are presented by which academy?', options: ['BAFTA', 'The Recording Academy', 'ASCAP', 'Billboard'], correctIndex: 1 },
    { question: 'Who wrote "Imagine"?', options: ['Paul McCartney', 'Ringo Starr', 'George Harrison', 'John Lennon'], correctIndex: 3 },
    { question: 'What genre is associated with artists like Tupac and Notorious B.I.G.?', options: ['R&B', 'Hip-Hop', 'Soul', 'Reggae'], correctIndex: 1 },
    { question: 'Which band had members Mick Jagger and Keith Richards?', options: ['The Beatles', 'The Who', 'The Rolling Stones', 'Led Zeppelin'], correctIndex: 2 },
    { question: 'What is the name of Beyoncé\'s alter ego?', options: ['Sasha Grey', 'Sasha Fierce', 'Queen Bey', 'Destiny'], correctIndex: 1 },
    { question: 'In music, what does "forte" mean?', options: ['Slow', 'Fast', 'Soft', 'Loud'], correctIndex: 3 },
    { question: 'Which artist released the album "Purple Rain"?', options: ['David Bowie', 'Prince', 'Michael Jackson', 'Jimi Hendrix'], correctIndex: 1 },
  ],
  'Technology': [
    { question: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Processing Unit', 'Central Program Utility', 'Core Processing Unit'], correctIndex: 0 },
    { question: 'Who co-founded Apple with Steve Wozniak?', options: ['Bill Gates', 'Steve Jobs', 'Jeff Bezos', 'Mark Zuckerberg'], correctIndex: 1 },
    { question: 'What does HTML stand for?', options: ['Hyper Transfer Markup Language', 'HyperText Markup Language', 'High-Tech Modern Language', 'Hyperlink Text Method Language'], correctIndex: 1 },
    { question: 'In what year was the World Wide Web invented?', options: ['1985', '1989', '1991', '1995'], correctIndex: 1 },
    { question: 'What does RAM stand for?', options: ['Read Access Memory', 'Random Access Memory', 'Rapid Action Memory', 'Runtime Application Module'], correctIndex: 1 },
    { question: 'Which company makes the Android operating system?', options: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2 },
    { question: 'What does "AI" stand for in technology?', options: ['Automated Interface', 'Automatic Input', 'Artificial Intelligence', 'Advanced Integration'], correctIndex: 2 },
    { question: 'Which programming language is named after a coffee?', options: ['Python', 'Ruby', 'Java', 'C++'], correctIndex: 2 },
    { question: 'What is the most visited website in the world?', options: ['Facebook', 'YouTube', 'Google', 'Amazon'], correctIndex: 2 },
    { question: 'What does USB stand for?', options: ['Universal Serial Bus', 'Unified System Base', 'Universal System Board', 'Unified Serial Bus'], correctIndex: 0 },
    { question: 'Which company developed the ChatGPT AI?', options: ['Google', 'Microsoft', 'OpenAI', 'Meta'], correctIndex: 2 },
    { question: 'What is the binary representation of the number 10?', options: ['0101', '1000', '1010', '1100'], correctIndex: 2 },
    { question: 'Who founded Microsoft?', options: ['Steve Jobs', 'Elon Musk', 'Bill Gates', 'Jeff Bezos'], correctIndex: 2 },
    { question: 'What does "GPU" stand for?', options: ['General Purpose Unit', 'Graphics Processing Unit', 'Global Program Utility', 'Game Processing Unit'], correctIndex: 1 },
    { question: 'Which social media platform uses the "tweet"?', options: ['Instagram', 'Facebook', 'Twitter/X', 'LinkedIn'], correctIndex: 2 },
    { question: 'What language is primarily used for styling web pages?', options: ['HTML', 'JavaScript', 'CSS', 'PHP'], correctIndex: 2 },
    { question: 'In what year was the iPhone first released?', options: ['2005', '2006', '2007', '2008'], correctIndex: 2 },
    { question: 'What does "URL" stand for?', options: ['Universal Resource Link', 'Uniform Resource Locator', 'Universal Record Locator', 'Unified Resource Library'], correctIndex: 1 },
    { question: 'Which company owns WhatsApp?', options: ['Google', 'Apple', 'Meta (Facebook)', 'Microsoft'], correctIndex: 2 },
    { question: 'What is the name of the Linux mascot?', options: ['Tux', 'Linus', 'Bash', 'Gnome'], correctIndex: 0 },
  ],
  'Food & Drink': [
    { question: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Mango', 'Avocado', 'Cucumber'], correctIndex: 2 },
    { question: 'Which country is sushi originally from?', options: ['China', 'Korea', 'Japan', 'Thailand'], correctIndex: 2 },
    { question: 'What type of pasta is shaped like small rice grains?', options: ['Penne', 'Orzo', 'Fusilli', 'Farfalle'], correctIndex: 1 },
    { question: 'Which nut is used to make marzipan?', options: ['Walnut', 'Hazelnut', 'Cashew', 'Almond'], correctIndex: 3 },
    { question: 'What is the national dish of Spain?', options: ['Tapas', 'Gazpacho', 'Paella', 'Churros'], correctIndex: 2 },
    { question: 'How many teaspoons make one tablespoon?', options: ['2', '3', '4', '5'], correctIndex: 1 },
    { question: 'Which fruit contains the most vitamin C?', options: ['Lemon', 'Orange', 'Guava', 'Kiwi'], correctIndex: 2 },
    { question: 'What is tofu made from?', options: ['Peas', 'Lentils', 'Soy beans', 'Chickpeas'], correctIndex: 2 },
    { question: 'Which country invented pizza?', options: ['Greece', 'France', 'USA', 'Italy'], correctIndex: 3 },
    { question: 'What is the primary ingredient of hummus?', options: ['Lentils', 'Chickpeas', 'Kidney beans', 'Broad beans'], correctIndex: 1 },
    { question: 'What are the two main ingredients of a Margherita pizza?', options: ['Pepperoni & cheese', 'Tomato & mozzarella', 'Basil & chicken', 'Olives & feta'], correctIndex: 1 },
    { question: 'Which spice comes from the Crocus flower?', options: ['Turmeric', 'Paprika', 'Saffron', 'Cumin'], correctIndex: 2 },
    { question: 'What is the most consumed beverage in the world after water?', options: ['Coffee', 'Tea', 'Milk', 'Juice'], correctIndex: 1 },
    { question: 'What is a Granny Smith?', options: ['A cheese', 'An apple', 'A grape', 'A tomato'], correctIndex: 1 },
    { question: 'Which vitamin is found in citrus fruits?', options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'], correctIndex: 2 },
    { question: 'Brie and Camembert are types of what?', options: ['Wine', 'Bread', 'Cheese', 'Ham'], correctIndex: 2 },
    { question: 'What grain is used to make sake?', options: ['Wheat', 'Corn', 'Barley', 'Rice'], correctIndex: 3 },
    { question: 'What is the world\'s most expensive spice by weight?', options: ['Vanilla', 'Saffron', 'Cardamom', 'Truffle'], correctIndex: 1 },
    { question: 'What gives red wine its colour?', options: ['Tannins', 'Anthocyanins in grape skins', 'Sulfites', 'Fermentation byproducts'], correctIndex: 1 },
    { question: 'Which country produces the most coffee?', options: ['Colombia', 'Vietnam', 'Ethiopia', 'Brazil'], correctIndex: 3 },
  ],
  'Nature': [
    { question: 'What is the fastest land animal?', options: ['Lion', 'Leopard', 'Cheetah', 'Ostrich'], correctIndex: 2 },
    { question: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correctIndex: 1 },
    { question: 'What is the largest living structure on Earth?', options: ['Amazon Rainforest', 'Great Wall of China', 'Great Barrier Reef', 'Sahara Desert'], correctIndex: 2 },
    { question: 'Which is the only mammal capable of true flight?', options: ['Flying squirrel', 'Sugar glider', 'Bat', 'Flying lemur'], correctIndex: 2 },
    { question: 'What type of animal is a Komodo Dragon?', options: ['Snake', 'Crocodile', 'Lizard', 'Tortoise'], correctIndex: 2 },
    { question: 'How long is an elephant\'s pregnancy (gestation)?', options: ['12 months', '16 months', '18 months', '22 months'], correctIndex: 3 },
    { question: 'What is the collective noun for a group of wolves?', options: ['Pack', 'Pride', 'Herd', 'Colony'], correctIndex: 0 },
    { question: 'Which planet has the most active volcanoes in our solar system?', options: ['Mars', 'Venus', 'Io (moon of Jupiter)', 'Earth'], correctIndex: 2 },
    { question: 'What is the process by which a caterpillar becomes a butterfly?', options: ['Metamorphosis', 'Evolution', 'Transformation', 'Adaptation'], correctIndex: 0 },
    { question: 'What is the largest species of shark?', options: ['Great White', 'Tiger Shark', 'Whale Shark', 'Bull Shark'], correctIndex: 2 },
    { question: 'How many eyes does a bee have?', options: ['2', '3', '4', '5'], correctIndex: 3 },
    { question: 'What is the most venomous snake in the world?', options: ['King Cobra', 'Inland Taipan', 'Black Mamba', 'Russell\'s Viper'], correctIndex: 1 },
    { question: 'Which tree produces acorns?', options: ['Elm', 'Ash', 'Oak', 'Beech'], correctIndex: 2 },
    { question: 'What do you call a group of fish?', options: ['Pod', 'School', 'Flock', 'Colony'], correctIndex: 1 },
    { question: 'How long can a crocodile live?', options: ['30–40 years', '50–60 years', '70–80 years', '100+ years'], correctIndex: 2 },
    { question: 'What is the largest bird in the world?', options: ['Emu', 'Cassowary', 'Ostrich', 'Emperor Penguin'], correctIndex: 2 },
    { question: 'Which planet has the largest storm in the solar system?', options: ['Saturn', 'Neptune', 'Uranus', 'Jupiter'], correctIndex: 3 },
    { question: 'What colour is a polar bear\'s skin?', options: ['White', 'Pink', 'Yellow', 'Black'], correctIndex: 3 },
    { question: 'How long can a camel survive without water?', options: ['3 days', '7 days', '14 days', 'Several weeks'], correctIndex: 3 },
    { question: 'What is the name for a group of lions?', options: ['Pack', 'Herd', 'Pride', 'Colony'], correctIndex: 2 },
  ],
};

// Normalise topic string to best-match bank key
function findBankKey(topic) {
  if (!topic) return 'General Knowledge';
  const t = topic.toLowerCase().trim();
  // Exact match first
  for (const key of Object.keys(BANK)) {
    if (key.toLowerCase() === t) return key;
  }
  // Partial match
  for (const key of Object.keys(BANK)) {
    if (t.includes(key.toLowerCase()) || key.toLowerCase().includes(t)) return key;
  }
  return 'General Knowledge'; // default fallback
}

export function getFallbackQuestions(topic, count = 8) {
  const key = findBankKey(topic);
  const pool = [...BANK[key]];
  // Shuffle
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(count, pool.length));
}
